version: '3'

services:
  caproto_sim:
    build:
      context: .
      dockerfile: caproto-backend/Dockerfile_sim_server

  caproto_server:
    build:
      context: .
      dockerfile: caproto-backend/Dockerfile
    ports:
      - "7654:7654"

#  grafana:
#    image: grafana/grafana:7.3.7
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./docker_compose_config/grafana.ini:/etc/grafana/grafana.ini
#      - ./grafana-plugins:/grafana-plugins

  grafana:
    build:
      context: .
      dockerfile: ./Dockerfile_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker_compose_config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-plugins:/grafana-plugins
      - grafana-storage:/var/lib/grafana

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    depends_on:
      - grafana
      - caproto_server
    ports:
      - "8080:8080"
      - "443:443"

volumes:
    grafana-storage:
