### App Container ###

FROM nginx
COPY docker_compose_config/nginx_default.conf.ssl /etc/nginx/conf.d/default.conf
COPY docker_compose_config/nginx_cert.crt /etc/nginx/conf.d/nginx_cert.crt
COPY docker_compose_config/nginx_cert.key /etc/nginx/conf.d/nginx_cert.key
