FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip

RUN pip3 install caproto

CMD python3 -m caproto.ioc_examples.random_walk --list-pvs
